apiVersion: apps/v1
kind: Deployment
metadata:
  #namespace: frontend
  name: currency-dep
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: currency
  template:
    metadata:
      labels:
        app: currency
    spec:
      containers:
      - name: currency-con
        image: node:12-alpine
        command: ['sh', '-c', 'echo The app is running! && sleep 3600']
        ports:
        - containerPort: 7000
        resources:
          limits:
            cpu: 200m
          requests:
            cpu: 100m
---
apiVersion: v1
kind: Service
metadata:
  name: currency
spec:
  selector:
    app: currency
  ports:
  - port: 7000
    targetPort: 7000
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: currency-dep
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: currency-dep
  minReplicas : 1
  maxReplicas : 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
